### ISSUE TITLE
您好,执行报错,似乎是全局变量在多线程下为None,有什么方法能加个锁控制一下呢，谢谢。

### ISSUE THREAD

**Issue by youth95** [AaronHeee/Neural-Attentive-Item-Similarity-Model#4]
报错信息
Traceback (most recent call last):
  File "FISM.py", line 212, in <module>
    training(args.pretrain, model, dataset, args.epochs, args.num_neg)
  File "FISM.py", line 139, in training
    batches = data.shuffle(dataset, model.batch_choice, num_negatives)
  File "C:\projects\Neural-Attentive-Item-Similarity-Model-master\Batch_gen.py", line 33, in shuffle
    return _preprocess(_get_train_batch_user)
  File "C:\projects\Neural-Attentive-Item-Similarity-Model-master\Batch_gen.py", line 64, in _preprocess
    res = pool.map(get_train_batch, range(_num_batch))
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value

**Comment by muyunping123** [comment]
请问一下您是怎么解决这个问题的呢
